// frontend/components/Forms/TextInput.tsx
import React, { forwardRef, useEffect, useImperativeHandle, useRef } from 'react';

export default forwardRef(function TextInput(
    { type = 'text', className = '', isFocused = false, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { isFocused?: boolean },
    ref
) {
    const input = useRef<HTMLInputElement>(null);

    useImperativeHandle(ref, () => ({
        focus: () => input.current?.focus(),
    }));

    useEffect(() => {
        if (isFocused) {
            input.current?.focus();
        }
    }, [isFocused]);

    return (
        <input
            {...props}
            type={type}
            className={
                'rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 ' +
                className
            }
            ref={input}
        />
    );
});

// resources/js/Components/TextInput.vue
<template>
    <input
        class="border-slate-300 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300 focus:border-indigo-500 dark:focus:border-indigo-600 focus:ring-indigo-500 dark:focus:ring-indigo-600 rounded-md shadow-sm"
        v-model="model"
        ref="input"
    />
</template>

<script setup>
import { onMounted, ref } from 'vue';

const model = defineModel({
    type: String,
    required: true,
});

const props = defineProps({
    isFocused: {
        type: Boolean,
        default: false,
    },
});

const input = ref(null);

onMounted(() => {
    if (props.isFocused) {
        input.value.focus();
    }
});

defineExpose({ focus: () => input.value.focus() });
</script>
